### ISSUE TITLE
Problem in calculating package size

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#10]
In the case below I have 8.39 Gb of content on an 8Gb card. Might be a problem with rounding?
![capture d ecran 2018-10-17 a 10 46 25](https://user-images.githubusercontent.com/21675885/47074110-058dac00-d1fa-11e8-9d66-75fbcf1ef218.png)

**Comment by rgaudin** [comment]
Yeah there's a bug ; calculations changed a bit in the desktop software lately and needs to be backported to the cardshop.

**Comment by rgaudin** [comment]
Fixed.
