### ISSUE TITLE
Incorrect contact detail in confirmation email

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#100]
Users creating an order get the following confirmation message:

_Should you have any question, your contact for this transaction is_ ``user`` _(copied)._

Whereas instead of ``user`` they should get ``popo`` or even ``support(at)kiwix.org``

**Comment by Popolechien** [comment]
Ah, correction: it looks like this incorrect user info only if there is no admin account in the silo.

**Comment by kelson42** [comment]
I propose instead contact+cardshop@kiwix.org... which would allow easy post filtering.

**Comment by Popolechien** [comment]
This is what I thought initially, but then realize that as we're still very much testing with clients I'd rather like to be notified quickly (I only go to the ticket management system once a day).
