### ISSUE TITLE
Config fields should not accept special characters

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#101]
(I'm pretty sure I've seen this issue before but can't find the ticket)

A user tried to create a configuration whose admin password included an exclamation mark. The installer failed pretty quickly with ``Invalid argument for admin_password`` as error log. I've opened an issue on Framagit ([#317](https://framagit.org/ideascube/kiwix-hotspot/issues/317)), but overall it'd be nice if the shop would recognize and flag special characters in the config file (ie before the installation is even started).

**Comment by rgaudin** [comment]
Duplicate of #83
