### ISSUE TITLE
Writer pending

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#103]
Either I did not get the email (checked but nada), or the writer is stuck somewhere:
I've ordered a physical card and though I got confirmation that the image had been made and was being uploaded, four days later I'm still waiting to hear from the writer (I checked, it's on).
FWIW the job I'm talking about is https://cardshop.hotspot.kiwix.org/all-orders/5d19a3f498c8bf5fcae47e81

**Comment by rgaudin** [comment]
Indeed a [previous run](https://cardshop.hotspot.kiwix.org/all-orders/5d14deb798c8bf0022e47df9) is going through #86.

Just restarted the workers so it should process the other ones in order now (I think there are 2).

We need to prioritize #86 as we're encountering it more than once a month I think.

**Comment by rgaudin** [comment]
I see the worker is picking up on the new task so closing this.
