### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [kiwix/cardshop#104]
Hi, I am a graphic designer and I would like to contribute my designing a logo for this project. Will start immediately if you permit me. Best regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by kelson42** [comment]
@Tobaloidee That is really kind of you. Lets see what @rgaudin and @Popolechien what they think about your idea.

**Comment by Popolechien** [comment]
Hi @Tobaloidee - thanks for the proposal! If you want to volunteer a logo, something around the hotspot might be an idea. You can get SVG versions of our logo here: https://commons.wikimedia.org/wiki/Category:Logos_of_Kiwix
And if we take it, it will have to integrate with this: 
https://commons.wikimedia.org/wiki/File:HOTSPOT_WEB_EN.pdf

**Comment by kelson42** [comment]
@Tobaloidee Here is the current logo of Kiwix Hotspot (the software behind the cardshop) https://github.com/kiwix/kiwix-hotspot/blob/master/kiwix-hotspot-logo.png. Maybe you can do something better. The Web favicon should also be considered.

**Comment by rgaudin** [comment]
Thanks, nothing to add!

**Comment by Tobaloidee** [comment]
Thanks for the response! will take note of all your feeds.. I will post my output here when done. :)

**Comment by Tobaloidee** [comment]
her's what I came up with..still open for your suggestions 

![cardshop-01](https://user-images.githubusercontent.com/36028424/60705318-6c462780-9f39-11e9-8c20-2bbefbb6aabe.png)

**Comment by Popolechien** [comment]
Well, both are very good!
I like the first one best as it better conveys the "Kiwix inside" idea. The second one would need to fix the beak contrast, but I have no idea how (different colors? Contour?). 
One comment on #1: this makes it look like the bird has a bit of a fat ass, would need some tweaking.
@kelson42 @rgaudin thoughts?

**Comment by Tobaloidee** [comment]
did a little tweaking 
![cardshop-02](https://user-images.githubusercontent.com/36028424/60749786-b67ae780-9fd1-11e9-8265-fc46d06b7af2.png)

**Comment by rgaudin** [comment]
This new version is my favorite. @Popolechien ?

**Comment by kelson42** [comment]
This new version is also my favorite.

**Comment by Popolechien** [comment]
@Tobaloidee never thought I'd write this on github but the ass is nice, thanks. Can we get a side-by-side of the new ass with the horizontal head (last prop) and the new ass with the head bobbing down (as in first prop)? Feel free to share your thinking as to why this or that, eh, I've spoken with enough designers to know things come for a reason.

Then I guess we will be ready to sign off on whichever most people here support. Thanks!

**Comment by Tobaloidee** [comment]
here it is! for the color preference. we can still change it whatever color you like it to be

![cardshop-04](https://user-images.githubusercontent.com/36028424/60850836-93477680-a223-11e9-8a1b-c1c0acb9f6a1.png)

**Comment by rgaudin** [comment]
No strong opinion but I think I prefer the one on the right.

**Comment by Popolechien** [comment]
I'll go for the one on the left and so would two of my colleagues here, but it's also close. 
@kelson42 any strong opinion on your side?

**Comment by kelson42** [comment]
My vote goes for the one on the left

**Comment by Popolechien** [comment]
@Tobaloidee Well the People have spoken: we'll take the one on the left! 
There isn't much we can give you in exchange except for eternal gratitude, but I do have a few cool stickers and goodies left, message me at contact / kiwix.org (ditto if you need access to the cardshop) :-)

**Comment by rgaudin** [comment]
Please send @Popolechien the source/hidef files so we can integrate that on the platform. Thanks again. Do we want to discuss color palette?

**Comment by kelson42** [comment]
Better, upload the high-resolution image (SVG?) to commons.wikimedia.org. We have a Kiwix category https://commons.wikimedia.org/wiki/Category:Kiwix

**Comment by Popolechien** [comment]
@rgaudin Re:color palette - the official logo is black/white. While some color wouldn't hurt, I'd rather have us as much on brand as possible as long as there isn't a global rethink about it.

**Comment by Tobaloidee** [comment]
here's the PR #108 for the logo upload & readme display.

you can download all the files and formats (SVG-Ai-PDF-PNG) of the new logo [HERE](https://drive.google.com/drive/u/1/folders/1odVSRXl65_7CFtEoDoh0AvECz74_GYdI)

**Comment by Popolechien** [comment]
Ok, files have been downloaded, thank you very much! 

@rgaudin can I let you merge the PR?
