### ISSUE TITLE
Clarify hotspot's URL in delivery message

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#109]
Follow up to #98 :

Users connect to the hotspot but a browser window does not always open. They are left trying to figure out how to access contents. It would therefore be useful to add the following line at the end of the download email:

"Once you are connected to the hotspot network, open a browser window and type http://goto.kiwix.hotspot or http://``configured_name``.hotspot to access it (beware that it is http, not https)."

**Comment by rgaudin** [comment]
We've circumvented this with the captive portal and have the URL on the bottom image. I think this is not relevant anymore. Please reopen if not with message.
