### ISSUE TITLE
Remove Version info from content selector

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#11]
The version column indicates the date at which the zim file was generated: I see no added value to this info as:
- People should not have a choice between the most recent and an older version of the zim file;
- Since we do not update (yet) our zim file on a daily basis this lower the signaled value of our content by making it look stale.

**Comment by rgaudin** [comment]
Agrees ; done.

![screen shot 2018-10-17 at 11 01 40 am](https://user-images.githubusercontent.com/57929/47082108-21924d00-d1fc-11e8-9e87-9137fa7f7960.png)
