### ISSUE TITLE
Gateway timeout on cardshop

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#113]
Cannot place an order. When trying again to post the order I got the following message:
``Error while saving… ConnectionErrorL --HTTPConnectionPool(host='scheduler.backend.cardshop.kiwixoffline.node.intern', port=80): Max retries exceeded with url: /warehouses/kiwix (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 113] No route to host'))``

**Comment by rgaudin** [comment]
No route to host indicates a network issue between the manager and the
scheduler. this is in sloppy’s hands.

Given the restarts we saw last night, and the fact that
https://status.sloppy.io reports outages, I’d wait until EOD.

**Comment by kelson42** [comment]
@Popolechien Sloppy is back so it should work. Please reopen the ticket if not.
@rgaudin I have open a ticket to have a small status page to bring clarity here https://github.com/kiwix/cardshop/issues/114
