### ISSUE TITLE
Provide an API to retrieve standard images URL

### ISSUE THREAD

**Issue by kelson42** [kiwix/cardshop#117]
The URL should be provided at the shop level. Considering that an updated image will be newly generated on a monthly base, we can not rely on a human action to update the URL. The shop should ask the cardshop where is located the image given a specific configuration.

See also https://github.com/kiwix/cardshop/issues/112

**Comment by kelson42** [comment]
@martin8032 That means that a Cardshop API call (after authentication) will be needed in www.kiwix.org to retrieve the proper image URL.

**Comment by martin8032** [comment]
Are we talking about the preliminary cardshop https://www.kiwix.org/en/downloads/kiwix-cardshop/ ?

We can add 1 .. n URLs per product. These URLs need to stay the same per image when the image is regenerated.

(As far as I can tell these URLs are not visible to the client who gets some kind of encoded link for his download.)

**Comment by rgaudin** [comment]
This has been implemented (see https://api.cardshop.hotspot.kiwix.org/auto-images/std-test/json) where `std-test` is the ID of the auto-image.

Though, this is not needed anymore, as per #180.
