### ISSUE TITLE
Create demo hotspot image

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#119]
Though the website will link to the free desktop-based installer, it would be good to show people what to expect from it (or the paid version). We should create a demo image that it easy to download (=small) yet helpful in showing what the cardshop can bring.
Contents:
Wikipedia for Schools (or Wikipedia 0.8?)
PhET Interactive Simulations
WikiMed Medical Encyclopedia
Raspberry Pi Stack Exchange 

This should make for a 16Gb card hosted on download.kiwix.org/hotspots under Hotspot_demo.img (hotspot name: kiwix)

**Comment by rgaudin** [comment]
Done.

**Comment by Popolechien** [comment]
Does it work on Raspberry W/4?

**Comment by rgaudin** [comment]
No. It's the images we created during Wikimania. We'll have to redo them with the next installer version. And every month anyway (see #112)
