### ISSUE TITLE
Content package not listed

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#12]
Added StackOverflow to my shopping cart but eventhough the size was added to the card, the item itself wasn't.
![capture d ecran 2018-10-17 a 10 53 35](https://user-images.githubusercontent.com/21675885/47074596-feb36900-d1fa-11e8-9894-5d5620dcf373.png)

**Comment by Popolechien** [comment]
Also I (obviously) can't remove it, even if clear the whole list.

**Comment by rgaudin** [comment]
Done (was due to `.` in package ID).
