### ISSUE TITLE
Enable automatic account creation on Cardshop

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#120]
Following up on #112, users should ultimately also be able to create an account from the cardshop's web page in order to generate their own custom cards.
![Capture d’écran 2019-08-13 à 11 48 45](https://user-images.githubusercontent.com/21675885/62932418-60634600-bdc0-11e9-9e02-8d6963634235.png)
While the first two will provide for ready-made cards that can be immediately downloaded, the third option above should take users to the payment page and also ask them for a user name& password, at which point (and upon payment confirmation) it will create an account on the cardshop.
It will also each month bill the user on their Credit card until the account is deleted.

**Comment by rgaudin** [comment]
Yes, as discussed this is a second step and should probably be enabled once we sort out how we want to refactor the UI (cf. the User/Org discussion we had) and improve the UI a bit.
We'd probably just ask for an email address though and generate a one-time password to prevent manipulating passwords on the shop.

**Comment by rgaudin** [comment]
Somewhat similar to #102

**Comment by Popolechien** [comment]
> We'd probably just ask for an email address though and generate a one-time password to prevent manipulating passwords on the shop.
Yes.

**Comment by kelson42** [comment]
After discussing with @rgaudin and @Popolechien, it has been decided that:
* For the "Wikipedia hotspot". a few languages would be available and the images would be pre-computed like for the "Demo Hotspot".
* The coherency beetween B2C and B2B portfolio/pricing should be secured
* The variables for the price are time/capacity to order SD card creation/not the amount of data.
* The principle would be that the visitor pay on the kiwix.org to get a voucher (a random not guessable string) which will allow to get what the user paid for on the cardshop.
