### ISSUE TITLE
504 Gateway timeout when trying to reach Orders section

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#124]
This is not systematic - but more often than not on a single session.

**Comment by Popolechien** [comment]
Ah, here is a log:
Environment:
Request Method: GET
Request URL: https://cardshop.hotspot.kiwix.org/all-orders/

Django Version: 2.2.4
Python Version: 3.7.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'manager']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "./manager/views/all_orders.py" in list
  47.         [OrderData(order) for order in as_items_or_none(*get_orders_list())],

Exception Type: TypeError at /all-orders/
Exception Value: 'NoneType' object is not iterable

**Comment by rgaudin** [comment]
Yes, I'm aware of this. Not sure there's a ticket though. It's a communication issue between the manager and the scheduler. thanks.

**Comment by kelson42** [comment]
Checking for this kind of error should be covered by #114

**Comment by rgaudin** [comment]
this wouldn't show up in the health check as this is a bug in that this specific request takes to long to process/retrieve: manager works, scheduler works but this page's logic is buggy.
