### ISSUE TITLE
Hotspot returns bad gateway for content

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#128]
I just created an image, which I ran on my raspberry pi: I can access the network and get to the landing page, however each and every content returns a 502 Bad Gateway error:
![Capture d’écran 2019-08-23 à 18 12 37](https://user-images.githubusercontent.com/21675885/63607043-cf674880-c5d1-11e9-9b5c-d41821fbeefd.png)

**Comment by kelson42** [comment]
@Popolechien This is a bug for Kiwix-Hotspot, not the cardshop. What is the configuration you have used?
@rgaudin This seems to be serious!

**Comment by Popolechien** [comment]
Transferred to Framagit ([323](https://framagit.org/ideascube/kiwix-hotspot/issues/323))
