### ISSUE TITLE
Prevent users from generating configs > 256 Gb

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#13]
Currently the interface rightly says it's not an option, but doesn't prevent users from doing it
![capture d ecran 2018-10-17 a 10 55 20](https://user-images.githubusercontent.com/21675885/47074717-45a15e80-d1fb-11e8-91ef-cce858d410aa.png)

**Comment by rgaudin** [comment]
I don't think we should prevent them from creating such configs:

* Would be very frustrating to assess what content to put in your config if you're not allowed to add content that would overcome the limit.
* Cardshop is not only about ordering physical card but also a way to work on presets without using the desktop version.

@kelson42 ?

**Comment by Popolechien** [comment]
Well they have to figure it out at some point, and the sooner the better - it's a lot more frustrating to have to hit "back" on your browser if you're about to order, particularly if the connection isn't that good.
At the very least maybe if the maximal size is reached circle the Selected Packages box area in red? (something visible - the current indicator isn't)

**Comment by rgaudin** [comment]
OK that makes sense. It is also the Desktop behavior (don't prevent but size in red).
