### ISSUE TITLE
Order has failed

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#133]
Two tasks from two separate users:
Order L134R5D6D / scheduler ID 5d6d3d7498c8bfad00fcdf5c is the latest

Log:
Starting to work on 5d6d3d7498c8bfad00fcdf5c
updating task #5d6d3d7498c8bfad00fcdf5c status to: building
Starting image creation
Starting /usr/bin/kiwix-hotspot cli --root --filename 5d6d3d7398c8bfad00fcdf37 --build-dir /data --config /data/5d6d3d7398c8bfad00fcdf37.json --size 64GB

installer started: <subprocess.Popen object at 0x7f6608d4a0f0>
periodic log upload..................
sending logs for task #5d6d3d7498c8bfad00fcdf5c.
periodic log upload..................
sending logs for task #5d6d3d7498c8bfad00fcdf5c.
periodic log upload..................
sending logs for task #5d6d3d7498c8bfad00fcdf5c.
periodic log upload..................
sending logs for task #5d6d3d7498c8bfad00fcdf5c.
installer failed: 0
collecting full terminated log
installer rc: 0
Traceback (most recent call last):
  File "worker/tasks/create.py", line 103, in run
    getattr(self, method)()
  File "worker/tasks/create.py", line 188, in build_image
    raise subprocess.SubprocessError("installer rc: {}".format(ps.returncode))
subprocess.SubprocessError: installer rc: 0
updating task #5d6d3d7498c8bfad00fcdf5c status to: failed_to_build
job is not alive
job crashed: installer rc: 0

**Comment by rgaudin** [comment]
https://framagit.org/ideascube/kiwix-hotspot/issues/328

Leaving this open until this is fixed in hotspot and new hotspot is deployed on the cardshop.

**Comment by rgaudin** [comment]
Done.
