### ISSUE TITLE
periodic tasks script is not executed

### ISSUE THREAD

**Issue by rgaudin** [kiwix/cardshop#136]
The `periodic_tasks` script is not run properly on the scheduler, either because it is not properly called or because the whole cron setup is incorrect.

This results in download files not being expired and thus not removed, resulting in TBs or useless data on the download warehouse.

**Comment by kelson42** [comment]
@rgaudin I believe we can close that one now, considering that images are uploaded to S3?

**Comment by rgaudin** [comment]
Fixed yesterday
