### ISSUE TITLE
Popup does not clear after de-hovering

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#14]
Use case: I generated a list, then removed some items. When the mouse hovers on the +/- symbol then the file name appears. In this case I removed bangla content and added english, but the mousehover text box did not clear properly (even when clicking randomly around the window).

As a quickfix, I would probably no show these text boxes in the first place.
![capture d ecran 2018-10-17 a 10 58 52](https://user-images.githubusercontent.com/21675885/47075061-fc9dda00-d1fb-11e8-9f87-c2b6d3e5447f.png)

**Comment by rgaudin** [comment]
Fixed.
