### ISSUE TITLE
Prevent order if configuration is empty

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#144]
A user launched an order ([L199R5E1E](https://cardshop.hotspot.kiwix.org/orders/L199R5E1E)) with no content in its config - this crashed the card creation. It would be better if the user would be prevented from ordering on an empty stomach (or config).

**Comment by kelson42** [comment]
@Popolechien This is definitely a bug
@rgaudin I think we should be able to create a card with no content

**Comment by rgaudin** [comment]
hum, there is no such thing as an empty config. I guess you mean without content (which is what's in the link you provided). That's a reasonable request and should not be prevented.

The problem in the order you mention is not in the installer (it worked fine) but in the download of the image on your physical worker.

The log indicates a network issue during the file transfer: it starts the FTP negociation, validates the credentials and then it retries a few times then gets the size, but ends up with a (`Failed to establish connection, cause: Connection refused`).

I just tried the same URI from my computer and it worked so I suggest you simply retry as this really looks like a network issue.
