### ISSUE TITLE
Error while ordering with `country` field left blank

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#151]
Scenario: 
I ordered a configuration, but the address used only had a name and email (phone, address and country were left blank).
Got the following error message :
`Error while saving… NOT NULL constraint failed: manager_order.recipient_country_code`

Yet the order seemingly went through (which is fine), but clearly this shouldn't be flagged as an error (just like Address and Phone # are not).

**Comment by kelson42** [comment]
Duplicate of #126

**Comment by rgaudin** [comment]
Yes
