### ISSUE TITLE
Enable usage collection

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#152]
Hotspots should be able to collect -and export- a limited amount of usage metrics:
- number of different devices;
- contents (zim files) being accessed, incl. relative "popularity" (ie how many times each content has been accessed);

The resulting data should be stored locally and/or easy to retrieve from the admin console.

**Comment by kelson42** [comment]
We need here to be carefully not reinventing the wheel in term of reporting. The current feature request is simple, but this might quickly move to something more complex. A clear technical proposal should be discussed before any implementation.

**Comment by rgaudin** [comment]
This has nothing to do with the Cardshop. Move it to hotspot maybe?
