### ISSUE TITLE
Why do silos each need a different email address?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#157]
Creating a silo requires an email address, but not two silos can have the same address. Why is that?
I'm also under the impression that these email addresses aren't being used, so I'm sort of confused as far as the need for such a feature goes.

**Comment by rgaudin** [comment]
As we are using _silos_ (_Organization_ actually) incorrectly to bypass I wouldn't care too much about this until we revamp the users/orgs thing.

The email address is supposed to be the point-of-contact for that org but yeah there's nothing requiring it to be unique IMO.

**Comment by Popolechien** [comment]
Ok thanks. I did find a workaround but yes in this case less is more :-)
