### ISSUE TITLE
Selected packages does not list selected tools

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#16]
Here for instance I had selected Khan Academy (10Gb), the file size has been correctly updated but it does not show in my package/config list.
![capture d ecran 2018-10-17 a 11 09 03](https://user-images.githubusercontent.com/21675885/47075558-1855b000-d1fd-11e8-843f-f5df63505509.png)

**Comment by rgaudin** [comment]
It's not a bug, it's related to #7 : Contents is wrongly named at it currently is *Static Contents* (aka ZIMs). Khan Academy is not a ZIM but a package (named *Tool* here).

Should we close this issue and work toward better integration of tools & contents in #7 ?

**Comment by Popolechien** [comment]
Well yes if it is not a bug but a feature, we want to remove that feature :-)
