### ISSUE TITLE
Cardshop does not update catalogue

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#166]
Wikipedia_en_all_maxi_2020-06 was updated 4 days ago and now weighs 89 Gb, however the cardshop lists it still at 78 Gb

![Capture d’écran 2020-07-06 à 08 38 03](https://user-images.githubusercontent.com/21675885/86563131-21079000-bf64-11ea-83c8-1ab3fdaeb569.png)

Since the link seems to be to a Wikipedia_en_all_maxi shortcut I don't know if it's impactful (maybe it will end up using the right file), but I would tend to think so.

**Comment by kelson42** [comment]
https://download.kiwix.org/library/ideascube.yml is not updated!

**Comment by kelson42** [comment]
@rgaudin https://download.kiwix.org/library/ideascube.yml is updated now. But value seems still wrong.

**Comment by rgaudin** [comment]
done
