### ISSUE TITLE
Delete erroneous zim file

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#167]
It was generated by mistake (listed as french whereas it's in English) and before we rolled out the Youtube2zim playlist functionality (hence duplicate with a slightly different name)

http://download.kiwix.org/zim/other/aimhi_en_geography_all_2020-06.zim

(I have since deleted the corresponding recipe)

**Comment by kelson42** [comment]
Should we delete that file?

**Comment by kelson42** [comment]
done
