### ISSUE TITLE
Writer gets mixed up between drive A and B

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#168]
I've started an order [(#5f436c2e006)](https://cardshop.hotspot.kiwix.org/orders/L295R5F43) and after a little while I receive two emails, one asking to insert a microSD card into `slot A` *and another one* for `slot B`
![Capture d’écran 2020-08-24 à 14 20 58](https://user-images.githubusercontent.com/21675885/91044116-1046d280-e615-11ea-97ab-c8252ac28793.png)

![Capture d’écran 2020-08-24 à 14 13 27](https://user-images.githubusercontent.com/21675885/91043817-8dbe1300-e614-11ea-8169-fc9621a0baec.png)

(both emails are sent at the same time and I only had one order going)

When I do click on B, I get a confirmation thanking me for the inserting in `Slot A`
![Screenshot_20200824_141343](https://user-images.githubusercontent.com/21675885/91043972-d4137200-e614-11ea-8f07-b34dd72f3f45.jpg)
and then a few minutes later the creation fails. I cannot go to activate slot B creation as the page is marked as not available (presumably because the order has been considered received and the process moved on, see #74)

**Comment by rgaudin** [comment]
OK, I don't know why you received two different emails ; that's funny.

It appears that the writing is currently in progress on Slot A, after an incorrect attempt without a card (possibly when you clicked the first time).
I'd like to remind you that the slot assignation is absolutely not guarantee across reboots… and that the machine rebooted a few days ago, following a power outage.
It may be that the slots are now inverted compared to what those were in the past. Please relabel the slots on your side as this will stay like this at least until next reboot.

I'm leaving this open for now as the two emails stuff remains unexplained.

**Comment by kelson42** [comment]
> I'd like to remind you that the slot assignation is absolutely not guarantee across reboots…

@rgaudin Do we have a ticket for this? This is really error prone. We should think about a solution to this problem IMO.

**Comment by rgaudin** [comment]
> > I'd like to remind you that the slot assignation is absolutely not guarantee across reboots…
> 
> 
> 
> @rgaudin Do we have a ticket for this? This is really error prone. We should think about a solution to this problem IMO.

I think it's documented. We discussed this when implementing : it's not possible to identify those USB devices (car readers) as nothing distinguishes them (same serial number).
Usb fd order based on physical port is not guaranteed neither (linux kernel)

**Comment by Popolechien** [comment]
@rgaudin Ok thanks for the clarification. In an interesting plot twist, I just received a confirmation email that the task on `slot A` was successfully completed and ready to ship (and it looks like the card was, in fact, successfully created, I just tested it) o_0

**Comment by kelson42** [comment]
@rgaudin We should open a ticket just to discuss this. I remember the discussion about it but I believe we should have a trace and ultimatively find a solution to that problem (maybe the solution is changing the HW or maybe using one or two slots which have different serials...).

**Comment by kelson42** [comment]
I don't believe we neet this ticket anymore
