### ISSUE TITLE
Integrate Africatik content to dashboard

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#174]
Might be worth moving to [/kiwix-hotspot](../../kiwix-hotspot/issues) : there will be a series of .exe and apk files corresponding to as many apps and educational programs to add to the cardshop.
We will need:
* the .exe and apk files (can be sent separately
* the corresponding landing pages for the hotspot so that end users can get a short description of what they are about to download/install

I can't assign @mulamba so simply pinging him here.

**Comment by Popolechien** [comment]
duplicate of https://github.com/kiwix/kiwix-hotspot/issues/543 ?

**Comment by kelson42** [comment]
@Popolechien Sorry did not saw this ticket before creating the ticket on kiwix-hotspot. We could consider it as a duplicate... but I guess a PR will be needed on cardshop as well. We can keep it open I believe.

**Comment by kelson42** [comment]
@rgaudin I guess this has been done via #550?
