### ISSUE TITLE
Does "Full text index" bring any valuable/actionable info?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#18]
It looks like it is mostly wiki-related, but what is the need for it, really?
![capture d ecran 2018-10-17 a 11 28 15](https://user-images.githubusercontent.com/21675885/47076768-cf532b00-d1ff-11e8-95da-91571baf9a9e.png)

**Comment by rgaudin** [comment]
It serves two purposes:

* Highlight that this content will be search-able (full-text).
* Should there be a content with two versions, one with and one-without, it might help choose wisely ; but I think nowadays all ZIMs are created with an index… @kelson42 ?
