### ISSUE TITLE
Deleting cardshop account should also cancel any payment

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#187]
If a user deletes their account their all payment authorizations with Stripe should also be canceled automatically. They shouldn't be charged for a service they explicitely do not want to use anymore.

**Comment by rgaudin** [comment]
Removed it from the project. This can (and should!) be added later. A message will be added to deletion page to invite them to contact us to cancel the subscription

**Comment by rgaudin** [comment]
We don't have subscriptions anymore so this has become irrelevant
