### ISSUE TITLE
Defaultsort by name rather than size

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#19]
And add a sorting option on top of each column so that people can either sort if by one or the other. I got confused thinking there was only one Wikipedia available in French and then only saw it much further down (same for WikiSource).
![capture d ecran 2018-10-17 a 11 31 50](https://user-images.githubusercontent.com/21675885/47076994-47215580-d200-11e8-9730-2b1fb69b20a8.png)

**Comment by rgaudin** [comment]
Done.
