### ISSUE TITLE
Hide units ?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/cardshop#197]
From the pad “Concept of "Quantity" (in cardshop unities, for example "16U") has not sense in a flatrate approach. It should not be displayed at the time of ordering and in the order report/email”

This is not clear to me. Either we support *unlimited access* or we don't but we can't do both.

Possibilities:

- Only physical cards are metered.
- We have two types of users: unlimited and limited.

Note that having *unlimited* users doesn't mean we can't record how much they consumed not act upon this later.

**Comment by Popolechien** [comment]
@rgaudin The way we've set things up for users, they can't order physical cards from us and never will. So at this stage unlimited access is simpler. 
But we could very well have the edge-case of someone setting up a business of bespoke cards and churning them out in a way that stresses our service to others. So yes if we could monitor or put an informal (ie, not seen by the user) cap at 10 or 15 images per month before we at least get a warning, that would be nice.

**Comment by rgaudin** [comment]
Ok, here's what I'm doing now:

- Users will now have a new property (`unlimited`)
- This property triggers display/hiding of *units* messages everywhere
- Also triggers the blockage or not of orders based on units
- Stripe-created accounts will be created as unlimited. Current accounts will stay in units-mode (except admins)

btw nb of images and resources doesn't directly match. 10x16GB images is 10h+ of creator resources but 10x256GB is 80h of resources…
