### ISSUE TITLE
Webshop configuration page should offer option to delete old configs

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#2]
Right now we can export but not simply delete. Also use "download" rather than "export".

![capture d ecran 2018-10-17 a 10 05 31](https://user-images.githubusercontent.com/21675885/47071586-34a11f00-d1f4-11e8-9193-5be89e07d5f6.png)

**Comment by rgaudin** [comment]
done.
![screen shot 2018-10-17 at 11 15 13 am](https://user-images.githubusercontent.com/57929/47082695-fd377000-d1fd-11e8-8f44-1694511a6509.png)
