### ISSUE TITLE
Orders page does not list all available configs

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#21]
I have three configs but the dropdown only shows two.
![capture d ecran 2018-10-17 a 11 39 47](https://user-images.githubusercontent.com/21675885/47077533-708eb100-d201-11e8-8a72-5352fa1b9c23.png)

**Comment by rgaudin** [comment]
The first one has no name ; fixed by making name mandatory in other issue.

**Comment by Popolechien** [comment]
No it did have a name. Should we reopen?
![capture d ecran 2018-10-17 a 11 50 16](https://user-images.githubusercontent.com/21675885/47078118-d7f93080-d202-11e8-8e99-c17bcbb7226c.png)

**Comment by rgaudin** [comment]
No this page falls back on project name if no name while the dropdown did not.

**Comment by Popolechien** [comment]
Ah "Kiwix hotspot" is a "no name" object - it's a bit confusing. I created a second config with the same name and got this on the order page
![capture d ecran 2018-10-17 a 11 51 51](https://user-images.githubusercontent.com/21675885/47078245-2eff0580-d203-11e8-848b-d90b082b6ddf.png)
