### ISSUE TITLE
Extend size of address field

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#22]
Currently 12 characters - push it maybe to 24 ("Orange South Africa" has 19)?
![capture d ecran 2018-10-17 a 11 45 14](https://user-images.githubusercontent.com/21675885/47077844-2954f000-d202-11e8-9cdf-dd0780b5605f.png)

**Comment by rgaudin** [comment]
done.
![screen shot 2018-10-17 at 10 53 10 am](https://user-images.githubusercontent.com/57929/47081671-de83aa00-d1fa-11e8-96f7-035d7d6c6308.png)
