### ISSUE TITLE
Fail message returns wrong link

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#222]
Order [#5fdc6c9e98c8bf437d0ea98f](https://cardshop.hotspot.kiwix.org/all-orders/5fdc6c9e98c8bf437d0ea98f) failed and the user received a notification email with an incorrect `Order ID` link pointing to https://cardshop.hotspot.kiwix.org/orders/f/5fdc6c9e98c8bf437d0ea98f (which returned an error) instead of all-orders/f/etcetcetc

**Comment by b-thebest** [comment]
Can I take up this issue?

**Comment by rgaudin** [comment]
@b-thebest sure

**Comment by b-thebest** [comment]
@rgaudin Thank you for assigning this task. I am new to open source community. Could you please provide me some source in order to understand problem more clearly and work on it.

**Comment by rgaudin** [comment]
The ticket seems suffisciently detailed. We send an email in case of error with an error. The link included in that email points to a wrong URL.
Check the source code to find what needs to be fixed

**Comment by b-thebest** [comment]
@rgaudin I have one doubt, Do we have to change link like this:
https://cardshop.hotspot.kiwix.org/orders/f/5fdc6c9e98c8bf437d0ea98f  -->  https://cardshop.hotspot.kiwix.org/all-orders/f/5fdc6c9e98c8bf437d0ea98f
or
https://cardshop.hotspot.kiwix.org/orders/f/5fdc6c9e98c8bf437d0ea98f  -->  https://cardshop.hotspot.kiwix.org/all-orders/f/etcetcetc

**Comment by rgaudin** [comment]
@b-thebest , acually trying to answer you I realized that the link is correct. The error mentioned by @Popolechien is due to that ID not existing.
@Popolechien would you still have that email? I wonder how you could get such a link.

**Comment by Popolechien** [comment]
@rgaudin Nope sorry, just checked and the email was deleted and the trash emptied :-/
