### ISSUE TITLE
Order should not let me chose media size

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#23]
It should by definition indicate the card's size - right now it let's me chose an 8Gb card for an 128Gb config. I don't see why/how the user should chose differently.
![capture d ecran 2018-10-17 a 11 48 18](https://user-images.githubusercontent.com/21675885/47078456-a2087c00-d203-11e8-9d78-119ea692d2c8.png)

**Comment by rgaudin** [comment]
This part's not complete… but should refuse any order for which the Media size is insufficient for the config.

You might want to choose higher media sizes though… 

We could also dynamically remove under sized media from the list on config change but I'm not sure there's much value in this.

**Comment by rgaudin** [comment]
When selecting wrong size:
![screen shot 2018-10-17 at 10 30 57 am](https://user-images.githubusercontent.com/57929/47080581-e68e1a80-d1f7-11e8-97f1-cb4bb7e837c4.png)

When the image is above 256GB
![screen shot 2018-10-17 at 10 31 10 am](https://user-images.githubusercontent.com/57929/47080555-d6763b00-d1f7-11e8-9b3a-f6c1fd7da9c5.png)

**Comment by Popolechien** [comment]
Fair enough, but that's adding one extra step (chosing the right size) when the service could do it already and present it as info rather than choice : what are the chances that someone with a 8Gb config orders a 128 Gb disk? At the very least the default size should be that corresponding to the end package.

**Comment by rgaudin** [comment]
I understand how getting rid of impossible choices is better so we should remove them and preselect the appropriate media but I am against removing the choice completely:

* An already-filled select box is as good as a label with the size IMO.
* While unlikely, use case exists where people want a 32GB card for a content that fits within 16GB: adding extra content afterwards for instance.
* It's not a productivity app. Getting an SD-card through the shop will probably be a week-long process if not more ; and users won't be placing 10 orders an hour.
* The main goal of the tool is to allow customization of the Hotspot. Reducing customization so cards be ordered in 2 clicks is not the goal I think.

**Comment by rgaudin** [comment]
Fixed by dynamically remove sizes that are impossible. Defaults to first media that can accept it ; leaving ability for user to choose higher amount or different kind of SD-card.
![screen shot 2018-10-17 at 5 40 53 pm](https://user-images.githubusercontent.com/57929/47105559-d6942c00-d233-11e8-9614-3b79cbf4dac0.png)
