### ISSUE TITLE
Update cardshop offer

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#238]
We've had a couple of people complain that the distinction between the 29/19 dollars wasn't clear. A user has been kind enough to provide a mockup for a potential improvement, so here it is:
![table_mockup](https://user-images.githubusercontent.com/21675885/114171071-13889780-9934-11eb-81bc-ed97bcd2b080.png)
Basically the idea is to make it clearer that they're the same, for different time periods, by merging the cells describing common points (keep the existing layout: only update the $19 text and merge the descriptors).

**Comment by rgaudin** [comment]
I believe this can be fixed by minor wording updates on the last one.
