### ISSUE TITLE
s3 is down and fails to upload

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#248]
See https://cardshop.hotspot.kiwix.org/orders/L515R6082 which failed with error being `503 Server Error: Service Unavailable for url: https://s3.us-west-1.wasabisys.com/org-kiwix-hotspot-cardshop-download/6082a66098c8bf54df24e1e0.img.torrent?compliance`

**Comment by rgaudin** [comment]
will look at it

**Comment by kelson42** [comment]
Seems to be back, i see successful tasks in zimfarm.

**Comment by rgaudin** [comment]
Thanks @Popolechien for the report. I was mislead by your message. The actual error is a network one: `ConnectionResetError: [Errno 104] Connection reset by peer` during upload. 

The `503` error happened when trying to set the *auto-delete* date which we attempt even on unsuccessful upload just-in-case (to not incomplete stuff in S3).

I see successful upload after this one so I'll close it as a network issue between the reset and wasabi. Hopefully it's not the sign of a larger problem as https://github.com/kiwix/kiwix-hotspot/issues/563 could suggest
