### ISSUE TITLE
Pricing attributes

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#25]
The current structure is 1Gb = 1 Unit. Hardware prices, however, are not linear: a quick benchmark on Amazon gave the following prices: 8 / 10 / 15 / 30 / 50 / 70 USD for 16/ 32/ 64/ 128/ 200 and 256 Gb, respectively, ie an 9x ratio between the smallest and biggest ones.

Prices will evolve but hopefully the ratio will remain within those boundaries. I would therefore attribute 2 Units to 16Gb cards (and below; if someone for some reason orders an empty-ish card, we still need to cover handling), then 3, 4, 8, 13 and 18 units.

**Comment by rgaudin** [comment]
As you can see in https://cardshop.hotspot.kiwix.org/admin/, Medias can be customized and have a `units_coef` attribute exactly for that purpose.

They also have a `kind` attribute so we could have different sets for `regular`, `high-speed` or `virtual` (for DL-only) Medias.

You can play with it but please document your chosen coefs elsewhere as data in the current shop will be reset later.

Closing as the feature is already there and what's left is configuration.
