### ISSUE TITLE
Health Check improperly report creator overload

### ISSUE THREAD

**Issue by rgaudin** [kiwix/cardshop#254]
At least just right now ; the health check reports impossibility to finish load within 24h while the worker is connected and idle.

<img width="1208" alt="Screen Shot 2021-04-30 at 08 32 48" src="https://user-images.githubusercontent.com/57929/116670164-ec4f4400-a98e-11eb-9459-860fe981dbfe.png">

<img width="1199" alt="Screen Shot 2021-04-30 at 08 32 53" src="https://user-images.githubusercontent.com/57929/116670155-e9545380-a98e-11eb-953e-5da73cc34dc3.png">

**Comment by kelson42** [comment]
Duplicate of #226 ?

**Comment by rgaudin** [comment]
No, not at all. Actually the worker was not alive (it's the first one in the screenshot).
