### ISSUE TITLE
Users should only be able to launch one order at a time

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#260]
In order to save resources and multiple meaningless image creations it would be useful that users only be allowed to order a new image if they don't have one being created already.
They should however be allowed to launch a new order as soon as the new image is available (e.g. when they receive the download email) rather than when the image has expired.

**Comment by kelson42** [comment]
@rgaudin This seems necessary if remove the ability for one random user to just suck all ot the resources and make all other wait and us getting a monitoring error.

**Comment by Popolechien** [comment]
Created also #262 to confirm that users should be able to cancel jobs.

I would also add an exception to the above request for admin accounts who may, in fact, have good reason to launch several requests in a row.
