### ISSUE TITLE
Shortversion of "GigaByte" should be "GB"

### ISSUE THREAD

**Issue by kelson42** [kiwix/cardshop#28]
It is current "GiB". See https://en.wikipedia.org/wiki/Gigabyte

**Comment by rgaudin** [comment]
We use both gigabyte and gigibyte in the cardshop (GB for SD card sizes)
and GiB for content sizes (as notes in another issue).
Where is it you found one that is not appropriately used ?

**Comment by kelson42** [comment]
@rgaudin Thanks for the explanation. First time I hear about term gigibyte. Difference is important from the tech perspective of course, but mixing both GiB and GB is really confusing from the user perspective.

**Comment by rgaudin** [comment]
I agree it's confusing but I don't have a better option:

* Use GiB everywhere: SD-card size would have weird capacity (although that would be only in config-edit where we display the size ; in orders and such we'd still display the name)
* Use GB everywhere: Contents would have different sizes than anywhere else (android app, kiwix websites ; particularly visible with largest files). For most people who wouldn't know/care about the size of contents, it would not matter much I guess.
* Use GB as both GB and GiB everywhere: might raise even more confusion as we might have similar sizes side-to-side which might not be compatible.
* Keep it as it is and wait to see if actual users notice/care. I'd bet most users would not notice or care as the actionable informations (SD size, free space remaining) are already there.

Note: We are using GB and GiB in Kiwix Hotspot exactly as it is in the cardshop and you did not notice :)

**Comment by kelson42** [comment]
OK, Then keep it like this for now.
