### ISSUE TITLE
cardshop is available on HTTP

### ISSUE THREAD

**Issue by kelson42** [kiwix/cardshop#29]
Like any other node, it should be available only via SSL.

**Comment by rgaudin** [comment]
It's [not possible with Sloppy](https://kb.sloppy.io/references/json-reference/json-reference-port-mappings).

Sloppy allows only one port per container to be exposed publicly and this port (whatever it is), it available through ports `80` and `443`. We can't disable HTTP.

**Comment by kelson42** [comment]
Y'a une option dans sloppy pour faire HTTP -> HTTPS, je vais l'activer et redemarrer le container.
