### ISSUE TITLE
Too many duplicates

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#31]
Looks like the library is not showing the last generated Stackexchange Zim files for a given topic, but all zims 

![capture d ecran 2018-10-18 a 15 06 33](https://user-images.githubusercontent.com/21675885/47156743-07359d80-d2e8-11e8-8413-d86827248708.png)

**Comment by rgaudin** [comment]
That's right ; it's the catalog, as for the Desktop version. That's why we had the version column in the first place I guess.

So we should only keep latest version of any package right ?

**Comment by Popolechien** [comment]
Yes please - the English list is long as it is, until there's better sorting there is no need to double the choice for little added value.

**Comment by kelson42** [comment]
@rgaudin None of the catalog should provide many version of the same contents, but many variants (with pictures, without pictures, etc...)

**Comment by kelson42** [comment]
@rgaudin "en" is right in the filename and wrong in as ZIM language meta data (also in the library.xml). "eng" is the opposite. Looks like we have wrong files here... I will remove them.

**Comment by kelson42** [comment]
Fixed
