### ISSUE TITLE
Interface crashes when selecting too many files

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#32]
I had about 20 small files on my list and then clicked "update" and got this error log:
´´´
Request Method: | GET
-- | --
https://cardshop.hotspot.kiwix.org/configurations/2
2.1.2
KeyError
'tw'
./manager/templatetags/manager.py in <listcomp>, line 56
/usr/local/bin/uwsgi
3.6.6
['.',  '',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages']
Thu, 18 Oct 2018 13:16:53 +0000

Error during template rendering
In template /app/manager/templates/base.html, error at line 0

1 | {% load static %}<html>
-- | --
<head>
<meta charset="utf-8">
<title>{% block title %}Kiwix Hotspot Cardshop{% endblock %}</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="shortcut icon" href="{% static 'img/kiwix-icon.png' %}" type="image/jpeg">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<style type="text/css">

Environment:

Request Method: GET
Request URL: https://cardshop.hotspot.kiwix.org/configurations/2

Django Version: 2.1.2
Python Version: 3.6.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'manager']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template error:
In template /app/manager/templates/base.html, error at line 0
   tw
   1 : {% load static %}<html>
   2 : <head>
   3 : 	<meta charset="utf-8">
   4 : 	<title>{% block title %}Kiwix Hotspot Cardshop{% endblock %}</title>
   5 : 	<meta http-equiv="X-UA-Compatible" content="IE=edge">	
   6 : 	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   7 : 	<link rel="shortcut icon" href="{% static 'img/kiwix-icon.png' %}" type="image/jpeg">
   8 : 	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
   9 : 	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
   10 : 	<style type="text/css">

Traceback:

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "./manager/views/config.py" in edit_configuration
  145.     return render(request, "edit_configuration.html", context)

File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py" in render
  36.     content = loader.render_to_string(template_name, context, request, using=using)

File "/usr/local/lib/python3.6/site-packages/django/template/loader.py" in render_to_string
  62.     return template.render(context, request)

File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render
  171.                     return self._render(context)

File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in _render
  163.         return self.nodelist.render(context)

File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py" in render
  150.             return compiled_parent._render(context)

File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in _render
  163.         return self.nodelist.render(context)

File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py" in render
  62.                 result = block.nodelist.render(context)

File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py" in render
  161.             values = self.sequence.resolve(context, ignore_failures=True)

File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in resolve
  698.                 new_obj = func(obj, *arg_vals)

File "./manager/templatetags/manager.py" in as_packages
  56.         for pid in json.loads(value) or []

File "./manager/templatetags/manager.py" in <listcomp>
  56.         for pid in json.loads(value) or []

Exception Type: KeyError at /configurations/2
Exception Value: 'tw'

GET
No GET data

POST
No POST data

FILES
No FILES data

COOKIES Variable | Value
-- | --
csrftoken | 'w5RJuWtIrb9hlt0ZUqziB9wB6yxAbzRJVuArYUut27vppMalhD5oIqYecQVW8zbj'
sessionid | 'ql9k2shu89s2xkfxa5ya9x8qqehibrm2'
messages | ('b84a683202cb5027259b83e56e44d5e8171051b5$[["__json_message",0,25,"Configuration '  'Updated successfuly !"]]')

META

Variable | Value
-- | --
CONTENT_LENGTH | ''
CONTENT_TYPE | ''
CSRF_COOKIE | 'w5RJuWtIrb9hlt0ZUqziB9wB6yxAbzRJVuArYUut27vppMalhD5oIqYecQVW8zbj'
CSRF_COOKIE_USED | True
DOCUMENT_ROOT | '/etc/nginx/html'
HTTP_ACCEPT | 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
HTTP_ACCEPT_ENCODING | 'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE | 'fr-CH,fr;q=0.9,en-CH;q=0.8,en;q=0.7,fr-FR;q=0.6,en-US;q=0.5'
HTTP_CACHE_CONTROL | 'max-age=0'
HTTP_CONNECTION | 'close'
HTTP_COOKIE | ('csrftoken=w5RJuWtIrb9hlt0ZUqziB9wB6yxAbzRJVuArYUut27vppMalhD5oIqYecQVW8zbj; '  'sessionid=ql9k2shu89s2xkfxa5ya9x8qqehibrm2; '  'messages="b84a683202cb5027259b83e56e44d5e8171051b5$[[\\"__json_message\\"\\0540\\05425\\054\\"Configuration '  'Updated successfuly !\\"]]"')
HTTP_DNT | '1'
HTTP_HOST | 'cardshop.hotspot.kiwix.org'
HTTP_REFERER | 'https://cardshop.hotspot.kiwix.org/configurations/2'
HTTP_UPGRADE_INSECURE_REQUESTS | '1'
HTTP_USER_AGENT | ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, '  'like Gecko) Chrome/69.0.3497.100 Safari/537.36')
HTTP_X_FORWARDED_FOR | '62.220.153.85'
HTTP_X_FORWARDED_PORT | '443'
HTTP_X_FORWARDED_PROTO | 'https'
PATH_INFO | '/configurations/2'
QUERY_STRING | ''
REMOTE_ADDR | '192.168.18.27'
REMOTE_PORT | '58058'
REQUEST_METHOD | 'GET'
REQUEST_SCHEME | 'http'
REQUEST_URI | '/configurations/2'
SCRIPT_NAME | ''
SERVER_NAME | ''
SERVER_PORT | '80'
SERVER_PROTOCOL | 'HTTP/1.1'
uwsgi.node | b'manager.frontend.cardshop.kiwixoffline.node.intern'
uwsgi.version | b'2.0.17.1'
wsgi.errors | <_io.TextIOWrapper name=2 mode='w' encoding='UTF-8'>
wsgi.file_wrapper | ''
wsgi.input | <uwsgi._Input object at 0x7effcec087e0>
wsgi.multiprocess | True
wsgi.multithread | False
wsgi.run_once | False
wsgi.url_scheme | 'https'
wsgi.version | (1, 0)

SETTINGS

Setting | Value
-- | --
ABSOLUTE_URL_OVERRIDES | {}
ADMINS | []
ADMIN_PASSWORD | '********************'
ALLOWED_HOSTS | ['*']
APPEND_SLASH | True
AUTHENTICATION_BACKENDS | ['django.contrib.auth.backends.ModelBackend']
AUTH_PASSWORD_VALIDATORS | '********************'
AUTH_USER_MODEL | 'auth.User'
BASE_DIR | '/app'
CACHES | {'default': {'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',              'LOCATION': '/data/cache',              'OPTIONS': {'MAX_ENTRIES': 1000},              'TIMEOUT': 86400}}
CACHE_MIDDLEWARE_ALIAS | 'default'
CACHE_MIDDLEWARE_KEY_PREFIX | '********************'
CACHE_MIDDLEWARE_SECONDS | 600
CARDSHOP_API_URL | '********************'
CONTENTS_FILE | '/app/contents.json'
CSRF_COOKIE_AGE | 31449600
CSRF_COOKIE_DOMAIN | None
CSRF_COOKIE_HTTPONLY | False
CSRF_COOKIE_NAME | 'csrftoken'
CSRF_COOKIE_PATH | '/'
CSRF_COOKIE_SAMESITE | 'Lax'
CSRF_COOKIE_SECURE | False
CSRF_FAILURE_VIEW | 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME | 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS | []
CSRF_USE_SESSIONS | False
DATABASES | {'default': {'ATOMIC_REQUESTS': False,              'AUTOCOMMIT': True,              'CONN_MAX_AGE': 0,              'ENGINE': 'django.db.backends.sqlite3',              'HOST': '',              'NAME': '/data/manager.sqlite3',              'OPTIONS': {},              'PASSWORD': '********************',              'PORT': '',              'TEST': {'CHARSET': None,                       'COLLATION': None,                       'MIRROR': None,                       'NAME': None},              'TIME_ZONE': None,              'USER': ''}}
DATABASE_ROUTERS | []
DATA_DIR | '/data'
DATA_UPLOAD_MAX_MEMORY_SIZE | 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS | 1000
DATETIME_FORMAT | 'N j, Y, P'
DATETIME_INPUT_FORMATS | ['%Y-%m-%d %H:%M:%S',  '%Y-%m-%d %H:%M:%S.%f',  '%Y-%m-%d %H:%M',  '%Y-%m-%d',  '%m/%d/%Y %H:%M:%S',  '%m/%d/%Y %H:%M:%S.%f',  '%m/%d/%Y %H:%M',  '%m/%d/%Y',  '%m/%d/%y %H:%M:%S',  '%m/%d/%y %H:%M:%S.%f',  '%m/%d/%y %H:%M',  '%m/%d/%y']
DATE_FORMAT | 'N j, Y'
DATE_INPUT_FORMATS | ['%Y-%m-%d',  '%m/%d/%Y',  '%m/%d/%y',  '%b %d %Y',  '%b %d, %Y',  '%d %b %Y',  '%d %b, %Y',  '%B %d %Y',  '%B %d, %Y',  '%d %B %Y',  '%d %B, %Y']
DEBUG | True
DEBUG_PROPAGATE_EXCEPTIONS | False
DECIMAL_SEPARATOR | '.'
DEFAULT_CHARSET | 'utf-8'
DEFAULT_CONTENT_TYPE | 'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER | 'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE | 'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL | 'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE | ''
DEFAULT_TABLESPACE | ''
DISALLOWED_USER_AGENTS | []
EMAIL_BACKEND | 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST | 'localhost'
EMAIL_HOST_PASSWORD | '********************'
EMAIL_HOST_USER | ''
EMAIL_PORT | 25
EMAIL_SSL_CERTFILE | None
EMAIL_SSL_KEYFILE | '********************'
EMAIL_SUBJECT_PREFIX | '[Django] '
EMAIL_TIMEOUT | None
EMAIL_USE_LOCALTIME | False
EMAIL_USE_SSL | False
EMAIL_USE_TLS | False
FILE_CHARSET | 'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS | None
FILE_UPLOAD_HANDLERS | ['django.core.files.uploadhandler.MemoryFileUploadHandler',  'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE | 2621440
FILE_UPLOAD_PERMISSIONS | None
FILE_UPLOAD_TEMP_DIR | None
FIRST_DAY_OF_WEEK | 0
FIXTURE_DIRS | []
FORCE_SCRIPT_NAME | None
FORMAT_MODULE_PATH | None
FORM_RENDERER | 'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS | []
INSTALLED_APPS | ['django.contrib.admin',  'django.contrib.auth',  'django.contrib.contenttypes',  'django.contrib.sessions',  'django.contrib.messages',  'django.contrib.staticfiles',  'manager']
INTERNAL_IPS | []
LANGUAGES | [('af', 'Afrikaans'),  ('ar', 'Arabic'),  ('ast', 'Asturian'),  ('az', 'Azerbaijani'),  ('bg', 'Bulgarian'),  ('be', 'Belarusian'),  ('bn', 'Bengali'),  ('br', 'Breton'),  ('bs', 'Bosnian'),  ('ca', 'Catalan'),  ('cs', 'Czech'),  ('cy', 'Welsh'),  ('da', 'Danish'),  ('de', 'German'),  ('dsb', 'Lower Sorbian'),  ('el', 'Greek'),  ('en', 'English'),  ('en-au', 'Australian English'),  ('en-gb', 'British English'),  ('eo', 'Esperanto'),  ('es', 'Spanish'),  ('es-ar', 'Argentinian Spanish'),  ('es-co', 'Colombian Spanish'),  ('es-mx', 'Mexican Spanish'),  ('es-ni', 'Nicaraguan Spanish'),  ('es-ve', 'Venezuelan Spanish'),  ('et', 'Estonian'),  ('eu', 'Basque'),  ('fa', 'Persian'),  ('fi', 'Finnish'),  ('fr', 'French'),  ('fy', 'Frisian'),  ('ga', 'Irish'),  ('gd', 'Scottish Gaelic'),  ('gl', 'Galician'),  ('he', 'Hebrew'),  ('hi', 'Hindi'),  ('hr', 'Croatian'),  ('hsb', 'Upper Sorbian'),  ('hu', 'Hungarian'),  ('ia', 'Interlingua'),  ('id', 'Indonesian'),  ('io', 'Ido'),  ('is', 'Icelandic'),  ('it', 'Italian'),  ('ja', 'Japanese'),  ('ka', 'Georgian'),  ('kab', 'Kabyle'),  ('kk', 'Kazakh'),  ('km', 'Khmer'),  ('kn', 'Kannada'),  ('ko', 'Korean'),  ('lb', 'Luxembourgish'),  ('lt', 'Lithuanian'),  ('lv', 'Latvian'),  ('mk', 'Macedonian'),  ('ml', 'Malayalam'),  ('mn', 'Mongolian'),  ('mr', 'Marathi'),  ('my', 'Burmese'),  ('nb', 'Norwegian Bokmål'),  ('ne', 'Nepali'),  ('nl', 'Dutch'),  ('nn', 'Norwegian Nynorsk'),  ('os', 'Ossetic'),  ('pa', 'Punjabi'),  ('pl', 'Polish'),  ('pt', 'Portuguese'),  ('pt-br', 'Brazilian Portuguese'),  ('ro', 'Romanian'),  ('ru', 'Russian'),  ('sk', 'Slovak'),  ('sl', 'Slovenian'),  ('sq', 'Albanian'),  ('sr', 'Serbian'),  ('sr-latn', 'Serbian Latin'),  ('sv', 'Swedish'),  ('sw', 'Swahili'),  ('ta', 'Tamil'),  ('te', 'Telugu'),  ('th', 'Thai'),  ('tr', 'Turkish'),  ('tt', 'Tatar'),  ('udm', 'Udmurt'),  ('uk', 'Ukrainian'),  ('ur', 'Urdu'),  ('vi', 'Vietnamese'),  ('zh-hans', 'Simplified Chinese'),  ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI | ['he', 'ar', 'fa', 'ur']
LANGUAGE_CODE | 'en-us'
LANGUAGE_COOKIE_AGE | None
LANGUAGE_COOKIE_DOMAIN | None
LANGUAGE_COOKIE_NAME | 'django_language'
LANGUAGE_COOKIE_PATH | '/'
LOCALE_PATHS | []
LOGGING | {'disable_existing_loggers': False,  'handlers': {'console': {'class': 'logging.StreamHandler'}},  'loggers': {'django': {'handlers': ['console'], 'level': 'INFO'},              'manager': {'handlers': ['console'], 'level': 'DEBUG'}},  'version': 1}
LOGGING_CONFIG | 'logging.config.dictConfig'
LOGIN_REDIRECT_URL | '/'
LOGIN_URL | '/login'
LOGOUT_REDIRECT_URL | '/'
MANAGERS | []
MANAGER_API_KEY | '********************'
MANAGER_API_USERNAME | '********************'
MEDIA_ROOT | '/data/media'
MEDIA_URL | '/media/'
MESSAGE_STORAGE | 'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE | ['django.middleware.security.SecurityMiddleware',  'django.contrib.sessions.middleware.SessionMiddleware',  'django.middleware.common.CommonMiddleware',  'django.middleware.csrf.CsrfViewMiddleware',  'django.contrib.auth.middleware.AuthenticationMiddleware',  'django.contrib.messages.middleware.MessageMiddleware',  'django.middleware.clickjacking.XFrameOptionsMiddleware']
MIGRATION_MODULES | {}
MIRROR | 'http://download.kiwix.org'
MONTH_DAY_FORMAT | 'F j'
NUMBER_GROUPING | 0
PASSWORD_HASHERS | '********************'
PASSWORD_RESET_TIMEOUT_DAYS | '********************'
PREPEND_WWW | False
ROOT_URLCONF | 'manager.urls'
SECRET_KEY | '********************'
SECURE_BROWSER_XSS_FILTER | False
SECURE_CONTENT_TYPE_NOSNIFF | False
SECURE_HSTS_INCLUDE_SUBDOMAINS | False
SECURE_HSTS_PRELOAD | False
SECURE_HSTS_SECONDS | 0
SECURE_PROXY_SSL_HEADER | None
SECURE_REDIRECT_EXEMPT | []
SECURE_SSL_HOST | None
SECURE_SSL_REDIRECT | False
SERVER_EMAIL | 'root@localhost'
SESSION_CACHE_ALIAS | 'default'
SESSION_COOKIE_AGE | 1209600
SESSION_COOKIE_DOMAIN | None
SESSION_COOKIE_HTTPONLY | True
SESSION_COOKIE_NAME | 'sessionid'
SESSION_COOKIE_PATH | '/'
SESSION_COOKIE_SAMESITE | 'Lax'
SESSION_COOKIE_SECURE | False
SESSION_ENGINE | 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE | False
SESSION_FILE_PATH | None
SESSION_SAVE_EVERY_REQUEST | False
SESSION_SERIALIZER | 'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE | 'manager.settings'
SHORT_DATETIME_FORMAT | 'm/d/Y P'
SHORT_DATE_FORMAT | 'm/d/Y'
SIGNING_BACKEND | 'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS | []
STATICFILES_DIRS | []
STATICFILES_FINDERS | ['django.contrib.staticfiles.finders.FileSystemFinder',  'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE | 'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT | '/data/static'
STATIC_URL | '/static/'
SUPPORT_EMAIL | 'stephane@kiwix.org'
TEMPLATES | [{'APP_DIRS': True,   'BACKEND': 'django.template.backends.django.DjangoTemplates',   'DIRS': [],   'OPTIONS': {'context_processors': ['django.template.context_processors.debug',                                      'django.template.context_processors.request',                                      'django.contrib.auth.context_processors.auth',                                      'django.contrib.messages.context_processors.messages']}}]
TEST_NON_SERIALIZED_APPS | []
TEST_RUNNER | 'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR | ','
TIME_FORMAT | 'P'
TIME_INPUT_FORMATS | ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE | 'UTC'
USE_I18N | True
USE_L10N | True
USE_THOUSAND_SEPARATOR | False
USE_TZ | True
USE_X_FORWARDED_HOST | False
USE_X_FORWARDED_PORT | False
WSGI_APPLICATION | 'manager.wsgi.application'
X_FRAME_OPTIONS | 'SAMEORIGIN'
YEAR_MONTH_FORMAT | 'F Y'

**Comment by rgaudin** [comment]
Yeah it's a bug ; don't worry about it.
