### ISSUE TITLE
Sending Email from Sloppy is not working

### ISSUE THREAD

**Issue by rgaudin** [kiwix/cardshop#33]
Emails are essential to the scheduler as it is though emails that it communicates with its users: recipients, clients (person who orders on the website) and writer operators.

scheduler uses SMTP to connect to a mailbox `cardshop@kiwix.org` to send emails. 

While this works locally, it doesn't work on Sloppy dues to Spam mitigation strategies (at Gandi but also at Gmail and probably any Email provider).

* External IP is unpredictable (although it is safe to assume it's from their German provider)
* Our external IP has-been/is/could-be listed in a RBL list of spamming IPs. We have no control over it and should it happen, our emails are rejected.
* Our external IP does not follow anti-spam guidelines regarding reverse records resulting in rejects.

To circumvent this, I have added support for [mailgun](https://www.mailgun.com/) HTTP API as an alternative (used if `MAILGUN_API_KEY` env is specified) to SMTP.

Mailgun offers 10,000 emails/month with their free package (see [pricing](https://www.mailgun.com/pricing)) and has a simple API. It's a dedicated service which handles emails correctly. Instructions to verify domains are easy and they have incoming email support (webhooks).

Amazon offers a similar service [AWS SES](https://aws.amazon.com/fr/ses/) but it seems the free 65K emails/months are only for apps hosted on AWS.

**Way forward:**

* Create a Kiwix account on Mailgun
* Follow DNS instructions for `cardshop.hotspot.kiwix.org` domain.
* Share credentials/API key.

**Comment by kelson42** [comment]
@rgaudin I have created an account and have send you the API key. That said, I have configured nothing on mailgun itself. Let me know if you want something special.
