### ISSUE TITLE
Support Image-creation only

### ISSUE THREAD

**Issue by rgaudin** [kiwix/cardshop#4]
Following discussion with @Popolechien, we might want the shop to offer image-creation service instead of physical SD-card.

Difference with the current workflow would be:

* No address
* Order complete once image is uploaded by creator worker
* Expiration of download link (a week ?)

Challenges:

* Support this use case (work)
* Blocks disk space for the duration of the download period on the warehouse
* How would we charge for this ?

**Comment by Popolechien** [comment]
Ok, the charging people issue is the easiest: people can buy units, and getting the link only would cost one unit. We can even make it free for small size, as freemium kind of model, or make people pay to have the file available for more than 24hrs (which would then be a fair incentive/compensation for larger files that take time to download): I think this is close to the WeTransfer model.

In terms of process, a choice button on the order page would be "Email me when file is ready" / "Send the card to a physical address" and open the relevant fields when ticked.

**Comment by rgaudin** [comment]
Agrees with second part but I don't think it should be free as it costs us money. The highest fixed cost is the server that generates the images and storing them is also expensive.

With a free service like this, Kiwix Hotspot (the desktop version) would have no purpose and we would be clogging our server with free image creations while paying customers would have to wait for the queue to empty…

**Comment by Popolechien** [comment]
Well if generating a small image (e.g. 16Gb) is fast enough, I would still advocate for that part at least to be free - we need to demonstrate value. We could also have a useful-yet-limited preset image ready for download (e.g. Wikimed) so that queueing isn't much of an issue.

**Comment by kelson42** [comment]
We do not have the infrastructure yet to do so IMO. We would be able to keep many weeks a few images but probably not dozen of them.

I would not put this feature in PROD without checking:
* Autodeletion strategy
* What happens if file is auto-deleted before user download it
* How to we deal if the warehouse server is full.

**Comment by rgaudin** [comment]
Definitely don’t have time for that in first version. As you said,
resources management is key

**Comment by rgaudin** [comment]
Implemented.
