### ISSUE TITLE
Missing notification that no address is available

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#40]
Currently when trying to place an order and no address has been registered, this is not really indicated as a missing information in the Recipient field. Maybe circle it in red and/or add text "no delivery address available".

![capture d ecran 2019-01-23 a 09 18 22](https://user-images.githubusercontent.com/21675885/51592447-f3559500-1eef-11e9-946c-a15969846939.png)

**Comment by rgaudin** [comment]
Right. Should be the same if there's no config as well.
