### ISSUE TITLE
Minor formatting issue on the welcome screen

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#42]
Part of the text reads:
"Both option require you to pay a fee <sup>using a prepaid units system</sup> but obviously the virtual one is cheaper.

We don't need the superscript, or even the text in it - if people have access, they've paid the fee already and know what they got themselves into.

**Comment by rgaudin** [comment]
OK to remove it but just to make sure we're on the same page, users might not be 100% on the payment mechanism:

* There is an Organization (FO)
* There's one account for the main client at that Organization (Paris)
* There are per-country accounts who are all tied to the Organization's balance but did not pay.

**Comment by Popolechien** [comment]
Yes. Maybe simply add "_if you do not have enough units to generate your images, contact your home organisation and copy "info@kiwix.org_"?
