### ISSUE TITLE
Replace Quantity/Link validity dropdown by text form

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#43]
The "Link validity" is not needed (it sounds rather greedy to triple the cost when tripling duration). Let's set a default to seven days (or 10, whatever), have it notified in the delivery email, and be done with it.

The Quantity dropdown could be replaced by a text field : it's easier to type 5 than dropdown>scroll down > select.

**Comment by rgaudin** [comment]
OK. makes sense.
I think we'll also need a way for admins to manually extend the validity of a file (in case the client/recipient requests it to you). Could you add an issue for that?
