### ISSUE TITLE
Change cardshop contact address

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#47]
Contact should be `hotspot at kiwix.org` - I don't think a personal address makes much sense (roles and responsabilities evolve, people go on vacations) and it's easier to track and manage tickets like this on Freshdesk.

**Comment by rgaudin** [comment]
OK ; @kelson42 can you create such address (redirection / otrs) ?

**Comment by kelson42** [comment]
@rgaudin done

**Comment by Popolechien** [comment]
I meant in the confirmation email I got about a minute ago...

**Comment by rgaudin** [comment]
You are using a personnal account (`stephane`). You can change the email address or create a generic user account if you'd prefer.
