### ISSUE TITLE
Download email should not set font-color

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#48]
I'm using Apple's desktop nightmore for my mail client and the download link appears black on black (I suspect that if the font color wasn't set it would work out fine?)
![capture d ecran 2019-01-23 a 15 01 06](https://user-images.githubusercontent.com/21675885/51611538-bdc8a000-1f1f-11e9-8e3d-82fcd1bd0e18.png)

**Comment by rgaudin** [comment]
Actually, for this button we set both foreground and background colors (white on solid blue).
I'll check and test and if we can't get it working we'll just not use colors and use the system button style.
