### ISSUE TITLE
Reword "General" configuration tab

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#5]
- Project name 
   -> Rename to "Hospot name" (otherwise we have two boxes next to one another with the word "name" in it, irrespective of explanations in field box. It also connects logically with the suggested "Kiwix hotspot" name);
   -> "Used to name your Box and its WiFi **network**" (missing network word);
- Name (as in Configuration name): add star * and make sure this one is mandatory;
- Region: there is a bit of French ("language en") and it should be clearer where that language will be applied, (e.g. "Hotspot interface language")
- Timezone: add UTC/GMT values if possible
- Security: are the admin/admin password fields mandatory if we install Aflatoun & co?
![capture d ecran 2018-10-17 a 10 10 41](https://user-images.githubusercontent.com/21675885/47071882-ffe19780-d1f4-11e8-8eaf-b3e389a38a16.png)

**Comment by rgaudin** [comment]
* Name & Project Name: done.
* Region: done
* Timezone: was there but I've added it on top with Europe/Paris as those are the most likely to be used.
* Security: already mandatory.

note: note redeployed yet.
