### ISSUE TITLE
Preview images in branding tab

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#6]
Currently not sure it's the image I want.
Also, is there a suggested size (e.g. square), or minimum (50*50px)?

Question: do we really need a favicon? People might get confused as to what this is, and honestly it's not that important on a tab (case in point: the cardshop does not have a favicon). I'm not asking to remove it, but I wouldn't see a drawback to branding all tabs with a default Kiwix favicon.

How many use cases do we plan of people adding their own CSS? If the answer is "not many", I'd probably remove that option for the time being or, better, only have it appear on Admin accounts along with the favicon option (my understanding is that there will be admin accounts like mine and user accounts for FO end-users)

![capture d ecran 2018-10-17 a 10 21 15](https://user-images.githubusercontent.com/21675885/47072488-6ca96180-d1f6-11e8-86dc-ea012aa33660.png)

**Comment by rgaudin** [comment]
There's currently a bug in displaying the actual images once added (permission on folder)

I am also upvoting default Kiwix branding for logo and favicon.

I'd prefer we keep favicon and CSS options yet arranged differently so it's clear those are advanced features which are optional and unlikely to be used.

**Comment by Popolechien** [comment]
Then maybe simply put those two on a second line with the (Optional / Advanced users) header?
