### ISSUE TITLE
Cardshop misreporting failed/successful status

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#63]
Order L22R5C6E (5c6ede1b98c8bf00246a310c / "Mobile Learning Week AR/FR/ES") is listed both as as ``failed`` and ``in progress``, whereas in fact I had creation confirmation and it is currently in the card writer.

**Comment by rgaudin** [comment]
Actually there's `L23R5C6E` (In Progress) and `L22R5C6E` (Failed – canceled).

I'm closing this as I think it's more related to #64.
