### ISSUE TITLE
Write email is not sent/received anymore

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#67]
Starting Friday 22nd there is no "insert card" email being sent after the regular "image has been created".
Inserting the card and then manually entering https://api.cardshop.hotspot.kiwix.org/tasks/writer/XYZ/confirm_inserted (with XYZ being task ID)
Leads to a page not found (404) error

**Comment by kelson42** [comment]
@Popolechien Still a valid bug?

**Comment by Popolechien** [comment]
@kelson42 I'll test again.

**Comment by rgaudin** [comment]
This is the auto-click feature of some app/readers/browsers. I though we had an issue for this but can't find it so leaving this one open.

**Comment by kelson42** [comment]
@rgaudin I don’t understand your last comment. It seems the email is sent (this is a really important one, but something else fails.... but what?).

**Comment by rgaudin** [comment]
@kelson42 for simplicity sake, when we ask the operator to insert a card, we send him a link to click once he has done it to confirm it's inserted and start the writing process.
We've seen that some browsers/email clients/etc read all links they find and *load* them. Some does this to display a preview of the link for instance.
In that case, the backend serves the link and interpret this as a confirmation and launches the writing process before the card is being inserted.

I'm closing this in favor of a better ticket #173
