### ISSUE TITLE
Order list does not clear up properly

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#71]
There currently are about 10 orders listed as "in progress" that have actually been completed.

**Comment by rgaudin** [comment]
Order status is refreshed on this page every hour (or when someone displays details) so there might be a 1h delay in this status.

It's not what's happening to all the orders you mention though: those are `pending_shipment`. It means that those are physical orders to which the operator (you?) did not set shipment details, thus acknowledging that the order was shipped.

Closing this but we shall probably open an issue to have the *latest status* dispplayed on that page.

**Comment by Popolechien** [comment]
My bad. I will open ticket.
