### ISSUE TITLE
Distinguish between failed and canceled orders

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#72]
Currently canceled orders are listed as failed. Clarifying that point in the list would be helpful to distinguish between actually failed orders and others that have been canceled for one reason or another.

**Comment by rgaudin** [comment]
OK. Those would stay under the *Cancelled* Tab though, right ?

**Comment by Popolechien** [comment]
Yes, yes. Instead of listing all of them as failed, simply update the wording to reflect those that simply were canceled.
![Capture d’écran 2019-03-27 à 10 23 32](https://user-images.githubusercontent.com/21675885/55064524-69a27f00-507a-11e9-986f-675f546be1ee.png)
