### ISSUE TITLE
Multiple card creation fails

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#82]
I created an order (config "Wau project") #5cd983a3047  and received a "Order has failed" notification a minute or so later. Tried again (#5cd99ddb3bd), with the same result.
Another user apparently tried a similar order, which failed similarly.

Interestingly, I tried to generate yet another order, but based on a different configuration, and haven't had a failure notification (yet).

**Comment by kelson42** [comment]
@Popolechien @rgaudin Seems quit critical to me.

**Comment by rgaudin** [comment]
`Invalid argument for 'admin_password'`.

Ça doit être dû au `@`. Je clos ce ticket et en ouvre un spécifique.
