### ISSUE TITLE
Restrictions on input fields should match requirements

### ISSUE THREAD

**Issue by rgaudin** [kiwix/cardshop#83]
* `project_name`
* `admin_account`
* `admin_password`
* `wifi_password`

Compare with hotspot-installer.

**Comment by kelson42** [comment]
Firs report with #83

**Comment by kelson42** [comment]
It seems that it is impossible to put accents in passwords... to be confirmed, fixed or managed.

**Comment by kelson42** [comment]
@rgaudin This bug is not trqcked at kiwix-hotpost level, this is important check happens at bot level.

**Comment by rgaudin** [comment]
the problem in the card shop is because we have checks on the installer so I don't understand your last comment
