### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#84]
Order L55R5CE3 / Scheduler ID 5ce3c43098c8bf5975706483
Crash notification after 9 minutes.
Log:

Starting to work on 5ce3c43198c8bf59757064a8
updating task #5ce3c43198c8bf59757064a8 status to: building
Starting image creation
Starting /usr/bin/kiwix-hotspot cli --root --filename 5ce3c43098c8bf5975706483 --build-dir /data --config /data/5ce3c43098c8bf5975706483.json --size 128GB

installer started: <subprocess.Popen object at 0x7f061bb107f0>
periodic log upload..................
sending logs for task #5ce3c43198c8bf59757064a8.
periodic log upload..................
sending logs for task #5ce3c43198c8bf59757064a8.
periodic log upload..................
sending logs for task #5ce3c43198c8bf59757064a8.
periodic log upload..................
sending logs for task #5ce3c43198c8bf59757064a8.
installer failed: 0
collecting full terminated log
installer rc: 0
Traceback (most recent call last):
  File "worker/tasks/create.py", line 103, in run
    getattr(self, method)()
  File "worker/tasks/create.py", line 188, in build_image
    raise subprocess.SubprocessError("installer rc: {}".format(ps.returncode))
subprocess.SubprocessError: installer rc: 0
updating task #5ce3c43198c8bf59757064a8 status to: failed_to_build
job is not alive
job crashed: installer rc: 0

**Comment by rgaudin** [comment]
Thanks, looking at the logs, it seems to be due to a network error between the worker and the download mirror.

```
[09:35:21] Error downloading http://download.kiwix.org/zim/gutenberg/gutenberg_fr_all_2018-10.zim to /data/kiwix-hotspot.cache/package_gutenberg_fr_all.fr-2018-10-22.zim
('Connection broken: IncompleteRead(973 bytes read, 51 more expected)', IncompleteRead(973 bytes read, 51 more expected))
[09:35:21] Installation failed: ('Connection broken: IncompleteRead(973 bytes read, 51 more expected)', IncompleteRead(973 bytes read, 51 more expected))
```

This is not a cardshop bug (so I'm removing the label). It might be an installer one but I doubt it to be. Might be a download server issue (sending incorrect data/headers) or a network issue.

Can you please retry it and let us know?

**Comment by Popolechien** [comment]
Tried again (L56R5CE3 / #5ce3c7a9529) and same thing happened after 15 minutes. Same network error but different package:
```
[09:52:22] --> Retrieving package_universcience-tv_fr_all.fr-2015-03-20.zim (13.07 GiB)
[                                                          ] 0%
[..........................................................] 100%
[09:56:08] Error downloading http://download.kiwix.org/zim/other/universcience-tv_fr_all_2015-03.zim to /data/kiwix-hotspot.cache/package_universcience-tv_fr_all.fr-2015-03-20.zim
('Connection broken: IncompleteRead(706 bytes read, 318 more expected)', IncompleteRead(706 bytes read, 318 more expected))
[09:56:08] Installation failed: ('Connection broken: IncompleteRead(706 bytes read, 318 more expected)', IncompleteRead(706 bytes read, 318 more expected))
```

**Comment by rgaudin** [comment]
Thanks @Popolechien, I opened an issue on the installer. https://framagit.org/ideascube/kiwix-hotspot/issues/313

@kelson42, no change in the download server and/or `mirror.download` configuration lately (`Content-Length` header, throttling, etc) ?

**Comment by rgaudin** [comment]
Could you please retry again (compression on ZIM files is now disabled)?

**Comment by Popolechien** [comment]
@rgaudin Image created and uploaded successfully to warehouse! \o/

**Comment by rgaudin** [comment]
Great. So the gzip compression was probably the problem. We'll still switch to aria2c in the installer in the future to avoid this kind of things.
