### ISSUE TITLE
Allow purchase of Hotspot cards and images

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#85]
In the long term, we should have a payment service for people interested in buying credit or access to the cardshop. A short term solution would be to create a payment page via Stripe and send people there for payment, with the account creation being manually validated after purchase.

**Comment by kelson42** [comment]
An other approach would be that we create a classical shop (on a web shop platform) and there the customer just buy a license which can be used in the cardshop. This would be a lot easier/cheaper than transforming the cardshop in a full-featured online web shop.

**Comment by rgaudin** [comment]
Agrees with @kelson42. It would be a lot less maintenance this way.
Shop could be Kiwix generic and serve other purposes as well (merch, etc).

**Comment by Popolechien** [comment]
Thanks for your feedback. This particular ticket was meant for a short term solution: 
 https://www.kiwix.org/cardshop/

**Comment by Popolechien** [comment]
Ok we have a working solution (-ish) at the moment. Closing the ticket for the time being.
