### ISSUE TITLE
Credits are not re-credited after build failure

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#89]
I just noticed that in spite of what the notification email said, credits are not added back to the acccount after failure to build.

**Comment by kelson42** [comment]
I’m not really sure this should happen. Builds should not fail, and if this happen then admin should be notified and the build should be retried/fixed.

**Comment by rgaudin** [comment]
agrees yet that requires us to fix a few issues incurring failures that would fail again on retries :

* enforce forbidden inputs
* switch to OPDS.

**Comment by rgaudin** [comment]
@kelson42 I know you want to reduce number of bugs but we are loosing information here... do we have a ticket requesting retry on failures ?

**Comment by kelson42** [comment]
@rgaudin What is sure is that ticket won't be implemented. If someone wants something else, then new tickets has to be done.

To me the only thing which is clear, is that if a build fails then Stéphane (as app manager) and we (developers) need to be notified and then the bug analysed, the build restarted after or before a fix. I don't think I want an automatic retry here, even if I won't oppose if you have good arguments to require one.

**Comment by rgaudin** [comment]
The bug is : we say we will refund on failures while we don’t.
You closed that ticket for valid reasons as we want to pursue a different approach.

Without opening a ticket for that other approach we’re just loosing track of that bug (hence, loss of information).

**Comment by kelson42** [comment]
Ok, my request is that we rephrase this email. Where is that message stored in the source code?
