### ISSUE TITLE
Disable "view all" (addresses, orders, configs) for non-admin account

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#91]
This is a bit of a confidentiality issue. Should we open access to the cardshop to all, there would be a workaround by creating an org for each user, but it is simpler to keep them in a silo. with admins (=us) being able to oversee quickly all users/orders.

**Comment by rgaudin** [comment]
Yes, I agree. I think we discussed having a _Kiwix_ org that we manage for that purpose.

**Comment by Popolechien** [comment]
Woops, duplicate of #150
