### ISSUE TITLE
Send warning message to org admins when order fails

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#94]
Currently if a user's order fails, they will get a notification and hopefully will think of contacting support, but that's not a given. It would be good for org admins to be notified as well.

**Comment by rgaudin** [comment]
Admin (client aka you) are cc'ed on this email.

That's the one that says “_Your account will be refunded shortly and your contact, <em>{{ order.client.name }}</em>, will get in touch with you as well to work this situation out._”

Can you check your emails and confirm?

**Comment by Popolechien** [comment]
Well yes - I can confirm I never received a thing (I checked my spam folder as well) - neither at creation nor failure notification.

**Comment by rgaudin** [comment]
Fix `send_order_email_for()` for list targets (`cc` and `bcc`).

**Comment by rgaudin** [comment]
Actually it's not a bug. Just ran a failing test with me (reg@kiwix) as `client` (created order) and you (stephane@kiwix) as `recipient` (Kiwix HQ) and both the initial and failure emails are sent to both of us properly.

![Screen Shot 2019-06-19 at 4 13 40 PM](https://user-images.githubusercontent.com/57929/59782536-a662c880-92ad-11e9-9e58-da2431a45307.png)

![Screen Shot 2019-06-19 at 4 14 18 PM](https://user-images.githubusercontent.com/57929/59782545-a95db900-92ad-11e9-9f84-c8bac5f35e0c.png)

Both are sent to the recipient, with the client cc'ed.

**Comment by Popolechien** [comment]
Ok that's odd - I received yesterday's created / failed order notification, but again this morning did not receive anything 0_o

**Comment by rgaudin** [comment]
Order number?

**Comment by Popolechien** [comment]
L75R5D0B

**Comment by rgaudin** [comment]
OK, I found the problem.
In this case, since the person creating the Order (`client`) is the same as the recipient, you are not involve at all.

We should, indeed refactor our role/org strategy now that we have enough experience to document what we want.

**Comment by Popolechien** [comment]
Well basically I think we should **bcc:** (not cc) info@kiwix.org for every email that is sent out from the service at this stage.

**Comment by rgaudin** [comment]
OK we can do that in the mean time, but we'll have to define the general behavior anyway at some point :)

**Comment by Popolechien** [comment]
Yup. Right now I'd stay we're still in a artisanal phase - it's easier to follow / find out about issues and volumes are low. A more subtle set of warning rules will come when we roll out an automated ordering system :-)
