### ISSUE TITLE
Remove unnecessary error message if address is incomplete

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#97]
Started a card creation (#5d11b42f287) - the addressee only indicated her name and email address and all other fields were left empty, as the aim is only to get a download link. Upon saving the order, I got the following error message:
```Error while saving… NOT NULL constraint failed: manager_order.recipient_country_code```

She did not, in fact, indicate any country of residence as it is not relevant. The error message, besides being somewhat cryptic, is not necessary and might confuse users as I separately received a confirmation email that the order was accepted.

**Comment by rgaudin** [comment]
Reclassified as user should not see something like that. And I need to investigate the consequences of that (maybe manager Order hasn't been created?)

**Comment by kelson42** [comment]
@rgaudin Looks really similar to #126

**Comment by rgaudin** [comment]
Yep, shall be addressed in #126
