### ISSUE TITLE
Improve download instructions

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#98]
I realized that users that have created a image file are sent a download link when the image is ready but no further explanation is given as to what to do with it.

>Dear ``User``
>Your Hotspot Image is now ready to download until ``date``.
>Download ``Config name`` (``size``GB)
> You can download this file (and share its link freely) until ``date`` At that date, the file will be permanently removed.
> You can pause and resume its download as you wish. Yet, a download manager is recommended as the download duration can span accross days.
> ``(config summary, e.g. order ID, config name, size, etc.)``
> The Kiwix Hotspot Cardshop Team.

The summary at the end has no practical value. I recommend replacing this download invite with:
 
> Dear ``User``
> Your Hotspot Image is now ready to download. 
> Download Config3 - ``Config name`` (``size``GB)
> You can pause and resume your download as you wish, and even share this link freely until ``date`` (after which the file will be permanently deleted). If your connection is slow, use a download manager!
> To install the file onto a microSD card, we recommend [BalenaEtcher](https://www.balena.io/etcher/)
> 
> Have a nice day,
> The Kiwix Hotspot Cardshop Team.

**Comment by kelson42** [comment]
Here is the official doc from RPI https://www.raspberrypi.org/documentation/installation/installing-images/. The last paragraph might be copied.

**Comment by rgaudin** [comment]
Adding the link instead.

**Comment by rgaudin** [comment]
(of the paragraph, not Stephane's suggestion, which is good)
