### ISSUE TITLE
Simple(r) error message when size exceeded

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#99]
If a user tries to order a card that exceeds the allowed limit of 256Gb and orders a card/download anyway, then they are taken to a server log listing the error.
![Capture d’écran 2019-07-01 à 08 26 39](https://user-images.githubusercontent.com/21675885/60414960-14768c00-9bda-11e9-92bb-f64020f478ae.png)
It would be simpler if they would be shown a regular red ink error message (e.g. "Max card size exceeded. Please update configuration")

**Comment by rgaudin** [comment]
yes, this is a debug page so user should never see it.

**Comment by kelson42** [comment]
@rgaudin @Popolechien Still happening?

**Comment by Popolechien** [comment]
There is no error message per se, but it's not possible to push an order anymore because there is no corresponding media. However it is not clear that maximum size has been exceeded.
![image](https://user-images.githubusercontent.com/21675885/116785298-273d9e80-aa99-11eb-99ee-bafbac21739b.png)

**Comment by kelson42** [comment]
It is nice that there is no user visible exception. That said, I guess the ticket can not be closed because backend is not secured. @rgaudin You confirm.

**Comment by rgaudin** [comment]
No, it looks like it was a typo in the code that has been long fixed. Closing
